name: Deploy Flask App

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Change to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy files via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H hubertchen200.site >> ~/.ssh/known_hosts
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='.git' . licong@hubertchen200.site:/app/chat_service

    - name: Restart server
      run: |
        ssh -o StrictHostKeyChecking=no licong@hubertchen200.site << 'EOF'
          source /path/to/your/virtualenv/bin/activate
          cd /app/chat_service
          # Command to restart your Flask app, e.g., using gunicorn
          sudo systemctl restart chat_service.service
        EOF
